require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - bin/*
    - config/**/*
    - db/schema.rb
    - db/migrate/*

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false


