default: &default
  adapter: postgresql
  host: <%= ENV['DB_HOST'] || Rails.application.credentials.dig(:db, :host) %>
  port: <%= ENV['DB_PORT'] || Rails.application.credentials.dig(:db, :port) %>
  username: <%= ENV['DB_USERNAME'] || Rails.application.credentials.dig(:db, :username) %>
  password: <%= ENV['DB_PASSWORD'] || Rails.application.credentials.dig(:db, :password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  timeout: 5000

development:
  <<: *default
  database: real_estate_agency_development

test:
  <<: *default
  database: real_estate_agency_test
  host: localhost
  port: 5432
  username: dummytest
  password: password

production:
  <<: *default
  database: real_estate_agency_production
