name: Setup environment

runs:
  using: composite
  steps:
    - name: apt-get update
      run: sudo apt-get update
      shell: bash

    - name: Setup ruby and install gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.3
        bundler-cache: true

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install npm packages
      run: yarn install --pure-lockfile
      shell: bash
