# name: CI

# on:
#   push:
#     branches: master
#   pull_request:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   precompile:
#     runs-on: ubuntu-latest
#     env:
#       RAILS_ENV: test
#       RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}

#     steps:
#       - name: Git clone our repo
#         uses: actions/checkout@v3

#       - name: Prepare rails environment
#         uses: ./.github/actions/prepare

#       - name: Compile assets
#         run: |
#           bundle exec rake assets:clobber
#           bundle exec rake assets:precompile

#       - name: Cache assets
#         id: cache-assets
#         uses: actions/cache@v3
#         with:
#           key: cache-assets-v1-${{ runner.os }}-${{ github.ref }}
#           path: |
#             public/assets
#             app/assets/builds
#   rspec:
#     needs: [precompile]
#     runs-on: ubuntu-20.04
#     services:
#       db:
#         image: postgres:latest
#         ports: ['5432:5432']
#         options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
#         env:
#           POSTGRES_HOST: localhost
#           POSTGRES_DB: real_estate_agency_test
#           POSTGRES_USER: dummy
#           POSTGRES_PASSWORD: password
#     env:
#       RAILS_ENV: test
#       RAILS_MASTER_KEY: ${{ secrets.RAILS_TEST_KEY }}
#       DB_USERNAME: dummy
#       DB_PASSWORD: password

#     steps:
#       - name: Git clone our repo
#         uses: actions/checkout@v3

#       - name: Prepare rails environment
#         uses: ./.github/actions/prepare

#       - name: Setup db
#         run: bundle exec rake db:create db:schema:load --trace

#       - name: Restore cached assets
#         uses: actions/cache@v3
#         with:
#           path: |
#             public/assets
#             app/assets/builds
#           key: cache-assets-v1-${{ runner.os }}-${{ github.ref }}

#       - name: Run rspec
#         run: bundle exec rspec --format progress

#       - name: Upload coverage results
#         uses: actions/upload-artifact@v3
#         if: always()
#         with:
#           name: coverage-report
#           path: coverage
    # needs: [precompile]
    # runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:latest
    #     env:
    #       POSTGRES_USER: dummy
    #       PGUSER: dummy
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: real_estate_agency_test
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       - 5432/tcp

    # steps:
    #   - name: Git clone our repo
    #     uses: actions/checkout@v3

    #   - name: Prepare rails environment
    #     uses: ./.github/actions/prepare

    #   - name: Setup db
    #     run: bundle exec rake db:create db:schema:load --trace

    #   - name: Restore cached assets
    #     uses: actions/cache@v3
    #     with:
    #       path: |
    #         public/assets
    #         app/assets/builds
    #       key: cache-assets-v1-${{ runner.os }}-${{ github.ref }}

    #   - name: Run rspec
    #     run: bundle exec rspec --format progress

    #   - name: Upload coverage results
    #     uses: actions/upload-artifact@v3
    #     if: always()
    #     with:
    #       name: coverage-report
    #       path: coverage

  # rubocop:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Git clone our repo
  #       uses: actions/checkout@v3

  #     - name: Prepare rails environment
  #       uses: ./.github/actions/prepare

  #     - name: Run rubocop
  #       run: bundle exec rubocop





name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

services:
  postgres:
    image: postgres:latest
    ports: ["5432:5432"]
    env:
      POSTGRES_PASSWORD: password
    options: >-
      --health-cmd pg_isready
      --health-interval 10s
      --health-timeout 5s
      --health-retries 5

steps:
  - name: Checkout Repository
    uses: actions/checkout@v2
  - name: Set up Ruby
    uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
    with:
      ruby-version: 3.3.5
  - name: Install PostgreSQL client
    run: |
      sudo apt-get -yqq install libpq-dev
  - name: Cache Ruby Gems
    uses: actions/cache@v2
    with:
      path: vendor/bundle
      key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      restore-keys: |
        ${{ runner.os }}-gems-
  - name: Bundle Install
    run: |
      bundle config path vendor/bundle
      bundle install --jobs 4 --retry 3
  - name: Run Tests
    env:
      PG_DATABASE: postgres
      PG_HOST: localhost
      PG_USER: dummy
      PG_PASSWORD: password
      RAILS_ENV: test
      WITH_COVERAGE: true
      DISABLE_SPRING: 1
    run: |
      bin/rails db:setup
      bundle exec rake test
  - name: Upload Code Coverage
    uses: actions/upload-artifact@v2
    with:
      name: code-coverage
      path: coverage/
  - name: Rubocop Checks
    run: |
      bundle exec rubocop
